<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{cdb5c23c-b562-4f2f-82d6-ee339a1fb725}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fb_CallHandler : CallHandler;
    fb_MovementControl : MovementControl;
    fb_DoorControl : DoorControl;
	fb_DoorSensors : DoorSensors;
	fb_Lights : Lights;
	fb_TargetFloorLights : TargetFloorLights;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb_CallHandler();
fb_DoorControl();
fb_MovementControl();
fb_DoorSensors();
fb_Lights();
fb_TargetFloorLights();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="23" Count="0" />
      <LineId Id="12" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="36" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>